//
//  Country.swift
//  E-ROK-Package
//
//  Created by Fabien Koré on 03/08/2025.
//


// Sources/EROKCore/Country.swift
// E-ROK-Package
//
// Created by Fabien Koré on 10/06/2025.

import Foundation

public enum Country: String, CaseIterable, Identifiable, Codable {
    case none = ""
    case albania = "AL"
    case andorra = "AD"
    case austria = "AT"
    case belarus = "BY"
    case belgium = "BE"
    case bosniaHerzegovina = "BA"
    case bulgaria = "BG"
    case croatia = "HR"
    case cyprus = "CY"
    case czechRepublic = "CZ"
    case denmark = "DK"
    case estonia = "EE"
    case finland = "FI"
    case france = "FR"
    case germany = "DE"
    case greece = "GR"
    case hungary = "HU"
    case iceland = "IS"
    case ireland = "IE"
    case italy = "IT"
    case kosovo = "XK"
    case latvia = "LV"
    case liechtenstein = "LI"
    case lithuania = "LT"
    case luxembourg = "LU"
    case malta = "MT"
    case moldova = "MD"
    case monaco = "MC"
    case montenegro = "ME"
    case netherlands = "NL"
    case northMacedonia = "MK"
    case norway = "NO"
    case poland = "PL"
    case portugal = "PT"
    case romania = "RO"
    case serbia = "RS"
    case slovakia = "SK"
    case slovenia = "SI"
    case spain = "ES"
    case sweden = "SE"
    case switzerland = "CH"
    case ukraine = "UA"
    case unitedKingdom = "UK"
    case russia = "RU"
    case afghanistan = "AF"
    case armenia = "AM"
    case azerbaijan = "AZ"
    case bahrain = "BH"
    case bangladesh = "BD"
    case bhutan = "BT"
    case cambodia = "KH"
    case china = "CN"
    case georgia = "GE"
    case india = "IN"
    case indonesia = "ID"
    case iraq = "IQ"
    case israel = "IL"
    case japan = "JP"
    case jordan = "JO"
    case kazakhstan = "KZ"
    case kuwait = "KW"
    case kyrgyzstan = "KG"
    case laos = "LA"
    case lebanon = "LB"
    case malaysia = "MY"
    case maldives = "MV"
    case mongolia = "MN"
    case myanmar = "MM"
    case nepal = "NP"
    case oman = "OM"
    case pakistan = "PK"
    case philippines = "PH"
    case qatar = "QA"
    case saudiArabia = "SA"
    case singapore = "SG"
    case southKorea = "KR"
    case sriLanka = "LK"
    case syria = "SY"
    case tajikistan = "TJ"
    case thailand = "TH"
    case turkey = "TR"
    case turkmenistan = "TM"
    case unitedArabEmirates = "AE"
    case uzbekistan = "UZ"
    case vietnam = "VN"
    case yemen = "YE"
    case algeria = "DZ"
    case angola = "AO"
    case benin = "BJ"
    case botswana = "BW"
    case burkinaFaso = "BF"
    case burundi = "BI"
    case cameroon = "CM"
    case capeVerde = "CV"
    case centralAfricanRepublic = "CF"
    case chad = "TD"
    case coteDIvoire = "CI"
    case democraticRepublicCongo = "CD"
    case djibouti = "DJ"
    case egypt = "EG"
    case equatorialGuinea = "GQ"
    case eritrea = "ER"
    case eswatini = "SZ"
    case ethiopia = "ET"
    case gabon = "GA"
    case gambia = "GM"
    case ghana = "GH"
    case guinea = "GN"
    case guineaBissau = "GW"
    case kenya = "KE"
    case liberia = "LR"
    case libya = "LY"
    case madagascar = "MG"
    case malawi = "MW"
    case mali = "ML"
    case mauritania = "MR"
    case mauritius = "MU"
    case morocco = "MA"
    case mozambique = "MZ"
    case namibia = "NA"
    case niger = "NE"
    case nigeria = "NG"
    case rwanda = "RW"
    case senegal = "SN"
    case seychelles = "SC"
    case sierraLeone = "SL"
    case somalia = "SO"
    case southAfrica = "ZA"
    case southSudan = "SS"
    case sudan = "SD"
    case tanzania = "TZ"
    case togo = "TG"
    case tunisia = "TN"
    case uganda = "UG"
    case zambia = "ZM"
    case zimbabwe = "ZW"
    case australia = "AU"
    case fiji = "FJ"
    case newZealand = "NZ"
    case papuaNewGuinea = "PG"
    case samoa = "WS"
    case tonga = "TO"
    case vanuatu = "VU"
    case argentina = "AR"
    case bolivia = "BO"
    case brazil = "BR"
    case canada = "CA"
    case chile = "CL"
    case colombia = "CO"
    case costaRica = "CR"
    case cuba = "CU"
    case dominicanRepublic = "DO"
    case ecuador = "EC"
    case elSalvador = "SV"
    case guatemala = "GT"
    case haiti = "HT"
    case honduras = "HN"
    case jamaica = "JM"
    case mexico = "MX"
    case nicaragua = "NI"
    case panama = "PA"
    case paraguay = "PY"
    case peru = "PE"
    case unitedStates = "US"
    case uruguay = "UY"
    case venezuela = "VE"
    
    public var id: String { rawValue }
    
    public var displayName: String {
        switch self {
        case .none: return "Aucun"
        case .albania: return "Albanie"
        case .andorra: return "Andorre"
        case .austria: return "Autriche"
        case .belarus: return "Biélorussie"
        case .belgium: return "Belgique"
        case .bosniaHerzegovina: return "Bosnie-Herzégovine"
        case .bulgaria: return "Bulgarie"
        case .croatia: return "Croatie"
        case .cyprus: return "Chypre"
        case .czechRepublic: return "République tchèque"
        case .denmark: return "Danemark"
        case .estonia: return "Estonie"
        case .finland: return "Finlande"
        case .france: return "France"
        case .germany: return "Allemagne"
        case .greece: return "Grèce"
        case .hungary: return "Hongrie"
        case .iceland: return "Islande"
        case .ireland: return "Irlande"
        case .italy: return "Italie"
        case .kosovo: return "Kosovo"
        case .latvia: return "Lettonie"
        case .liechtenstein: return "Liechtenstein"
        case .lithuania: return "Lituanie"
        case .luxembourg: return "Luxembourg"
        case .malta: return "Malte"
        case .moldova: return "Moldavie"
        case .monaco: return "Monaco"
        case .montenegro: return "Monténégro"
        case .netherlands: return "Pays-Bas"
        case .northMacedonia: return "Macédoine du Nord"
        case .norway: return "Norvège"
        case .poland: return "Pologne"
        case .portugal: return "Portugal"
        case .romania: return "Roumanie"
        case .serbia: return "Serbie"
        case .slovakia: return "Slovaquie"
        case .slovenia: return "Slovénie"
        case .spain: return "Espagne"
        case .sweden: return "Suède"
        case .switzerland: return "Suisse"
        case .ukraine: return "Ukraine"
        case .unitedKingdom: return "Royaume-Uni"
        case .russia: return "Russie"
        case .afghanistan: return "Afghanistan"
        case .armenia: return "Arménie"
        case .azerbaijan: return "Azerbaïdjan"
        case .bahrain: return "Bahreïn"
        case .bangladesh: return "Bangladesh"
        case .bhutan: return "Bhoutan"
        case .cambodia: return "Cambodge"
        case .china: return "Chine"
        case .georgia: return "Géorgie"
        case .india: return "Inde"
        case .indonesia: return "Indonésie"
        case .iraq: return "Irak"
        case .israel: return "Israël"
        case .japan: return "Japon"
        case .jordan: return "Jordanie"
        case .kazakhstan: return "Kazakhstan"
        case .kuwait: return "Koweït"
        case .kyrgyzstan: return "Kirghizistan"
        case .laos: return "Laos"
        case .lebanon: return "Liban"
        case .malaysia: return "Malaisie"
        case .maldives: return "Maldives"
        case .mongolia: return "Mongolie"
        case .myanmar: return "Myanmar"
        case .nepal: return "Népal"
        case .oman: return "Oman"
        case .pakistan: return "Pakistan"
        case .philippines: return "Philippines"
        case .qatar: return "Qatar"
        case .saudiArabia: return "Arabie saoudite"
        case .singapore: return "Singapour"
        case .southKorea: return "Corée du Sud"
        case .sriLanka: return "Sri Lanka"
        case .syria: return "Syrie"
        case .tajikistan: return "Tadjikistan"
        case .thailand: return "Thaïlande"
        case .turkey: return "Turquie"
        case .turkmenistan: return "Turkménistan"
        case .unitedArabEmirates: return "Émirats arabes unis"
        case .uzbekistan: return "Ouzbékistan"
        case .vietnam: return "Vietnam"
        case .yemen: return "Yémen"
        case .algeria: return "Algérie"
        case .angola: return "Angola"
        case .benin: return "Bénin"
        case .botswana: return "Botswana"
        case .burkinaFaso: return "Burkina Faso"
        case .burundi: return "Burundi"
        case .cameroon: return "Cameroun"
        case .capeVerde: return "Cap-Vert"
        case .centralAfricanRepublic: return "République centrafricaine"
        case .chad: return "Tchad"
        case .coteDIvoire: return "Côte d'Ivoire"
        case .democraticRepublicCongo: return "République démocratique du Congo"
        case .djibouti: return "Djibouti"
        case .egypt: return "Égypte"
        case .equatorialGuinea: return "Guinée équatoriale"
        case .eritrea: return "Érythrée"
        case .eswatini: return "Eswatini"
        case .ethiopia: return "Éthiopie"
        case .gabon: return "Gabon"
        case .gambia: return "Gambie"
        case .ghana: return "Ghana"
        case .guinea: return "Guinée"
        case .guineaBissau: return "Guinée-Bissau"
        case .kenya: return "Kenya"
        case .liberia: return "Libéria"
        case .libya: return "Libye"
        case .madagascar: return "Madagascar"
        case .malawi: return "Malawi"
        case .mali: return "Mali"
        case .mauritania: return "Mauritanie"
        case .mauritius: return "Maurice"
        case .morocco: return "Maroc"
        case .mozambique: return "Mozambique"
        case .namibia: return "Namibie"
        case .niger: return "Niger"
        case .nigeria: return "Nigeria"
        case .rwanda: return "Rwanda"
        case .senegal: return "Sénégal"
        case .seychelles: return "Seychelles"
        case .sierraLeone: return "Sierra Leone"
        case .somalia: return "Somalie"
        case .southAfrica: return "Afrique du Sud"
        case .southSudan: return "Soudan du Sud"
        case .sudan: return "Soudan"
        case .tanzania: return "Tanzanie"
        case .togo: return "Togo"
        case .tunisia: return "Tunisie"
        case .uganda: return "Ouganda"
        case .zambia: return "Zambie"
        case .zimbabwe: return "Zimbabwe"
        case .australia: return "Australie"
        case .fiji: return "Fidji"
        case .newZealand: return "Nouvelle-Zélande"
        case .papuaNewGuinea: return "Papouasie-Nouvelle-Guinée"
        case .samoa: return "Samoa"
        case .tonga: return "Tonga"
        case .vanuatu: return "Vanuatu"
        case .argentina: return "Argentine"
        case .bolivia: return "Bolivie"
        case .brazil: return "Brésil"
        case .canada: return "Canada"
        case .chile: return "Chili"
        case .colombia: return "Colombie"
        case .costaRica: return "Costa Rica"
        case .cuba: return "Cuba"
        case .dominicanRepublic: return "République dominicaine"
        case .ecuador: return "Équateur"
        case .elSalvador: return "Salvador"
        case .guatemala: return "Guatemala"
        case .haiti: return "Haïti"
        case .honduras: return "Honduras"
        case .jamaica: return "Jamaïque"
        case .mexico: return "Mexique"
        case .nicaragua: return "Nicaragua"
        case .panama: return "Panama"
        case .paraguay: return "Paraguay"
        case .peru: return "Pérou"
        case .unitedStates: return "États-Unis"
        case .uruguay: return "Uruguay"
        case .venezuela: return "Venezuela"
        }
    }
}