//
//  DressCode.swift
//  E-ROK-Package
//
//  Created by Fabien Koré on 27/09/2025.
//


// Sources/SHIFT/DressCode.swift
// E-ROK-Package
//
// Created by Fabien Koré on 13/07/2025.

import Foundation

public enum DressCode: String, Codable, CaseIterable, Identifiable {
    case casual = "Casual"
    case smartCasual = "Smart Casual"
    case businessCasual = "Business Casual"
    case formal = "Formal"
    case blackTie = "Black Tie"
    case whiteTie = "White Tie"
    case cocktail = "Cocktail"
    case semiFormal = "Semi-Formal"
    case themed = "Themed"
    case elegant = "Elegant"
    case chic = "Chic"
    case sporty = "Sporty"
    case beachwear = "Beachwear"
    case vintage = "Vintage"
    case urban = "Urban"
    case glamorous = "Glamorous"
    case retro = "Retro"
    case festival = "Festival"
    case masquerade = "Masquerade"
    case casualChic = "Casual Chic"
    case eveningWear = "Evening Wear"
    case businessFormal = "Business Formal"
    case sportElegant = "Sport Elegant"
    case bohemian = "Bohemian"
    case goth = "Goth"
    case streetwear = "Streetwear"
    case ecoFriendly = "Eco-Friendly"
    case allWhite = "All White"
    case allBlack = "All Black"
    case colorCode = "Color Code"
    case formalCasual = "Formal Casual"
    case loungeWear = "Lounge Wear"
    case partyCasual = "Party Casual"
    case luxury = "Luxury"
    case noDressCode = "No Dress Code"
    case avantGarde = "Avant-Garde"
    case futuristic = "Futuristic"
    case cyberpunk = "Cyberpunk"
    case steampunk = "Steampunk"
    case dandy = "Dandy / Gentlemen"
    case rockRoll = "Rock 'n' Roll"
    case biker = "Biker / Cuir"
    case glamRock = "Glam Rock"
    case neonGlow = "Néon / Glow in the dark"
    case disco = "Disco / Paillettes"
    case fancyDress = "Déguisement / Fancy Dress"
    case cosplay = "Cosplay"
    case allRed = "All Red"
    case allBlue = "All Blue"
    case goldAndBlack = "Gold & Black"
    case summerChic = "Summer Chic"
    case winterChic = "Winter Chic"
    case resortChic = "Resort Chic"
    case pyjamaParty = "Pyjama Party"
    case halloween = "Halloween"
    case christmas = "Christmas Sweater / Noël"
    case rockabilly = "Rockabilly"
    case grunge = "Grunge"
    case indie = "Indie"
    case preppy = "Preppy"
    case safari = "Safari"
    case tropical = "Tropical / Hawaïen"
    case countryWestern = "Country / Western"
    case baroque = "Baroque"
    case minimalist = "Minimalist"
    case underground = "Underground"
    case hauteCouture = "Haute Couture"

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .casual: return "Casual"
        case .smartCasual: return "Smart Casual"
        case .businessCasual: return "Business Casual"
        case .formal: return "Formal"
        case .blackTie: return "Black Tie"
        case .whiteTie: return "White Tie"
        case .cocktail: return "Cocktail"
        case .semiFormal: return "Semi-Formal"
        case .themed: return "Themed"
        case .elegant: return "Elegant"
        case .chic: return "Chic"
        case .sporty: return "Sporty"
        case .beachwear: return "Beachwear"
        case .vintage: return "Vintage"
        case .urban: return "Urban"
        case .glamorous: return "Glamorous"
        case .retro: return "Retro"
        case .festival: return "Festival"
        case .masquerade: return "Masquerade"
        case .casualChic: return "Casual Chic"
        case .eveningWear: return "Evening Wear"
        case .businessFormal: return "Business Formal"
        case .sportElegant: return "Sport Elegant"
        case .bohemian: return "Bohemian"
        case .goth: return "Goth"
        case .streetwear: return "Streetwear"
        case .ecoFriendly: return "Eco-Friendly"
        case .allWhite: return "All White"
        case .allBlack: return "All Black"
        case .colorCode: return "Color Code"
        case .formalCasual: return "Formal Casual"
        case .loungeWear: return "Lounge Wear"
        case .partyCasual: return "Party Casual"
        case .luxury: return "Luxury"
        case .noDressCode: return "No Dress Code"
        case .avantGarde: return "Avant-Garde"
        case .futuristic: return "Futuristic"
        case .cyberpunk: return "Cyberpunk"
        case .steampunk: return "Steampunk"
        case .dandy: return "Dandy / Gentlemen"
        case .rockRoll: return "Rock 'n' Roll"
        case .biker: return "Biker / Cuir"
        case .glamRock: return "Glam Rock"
        case .neonGlow: return "Néon / Glow in the dark"
        case .disco: return "Disco / Paillettes"
        case .fancyDress: return "Déguisement / Fancy Dress"
        case .cosplay: return "Cosplay"
        case .allRed: return "All Red"
        case .allBlue: return "All Blue"
        case .goldAndBlack: return "Gold & Black"
        case .summerChic: return "Summer Chic"
        case .winterChic: return "Winter Chic"
        case .resortChic: return "Resort Chic"
        case .pyjamaParty: return "Pyjama Party"
        case .halloween: return "Halloween"
        case .christmas: return "Christmas Sweater / Noël"
        case .rockabilly: return "Rockabilly"
        case .grunge: return "Grunge"
        case .indie: return "Indie"
        case .preppy: return "Preppy"
        case .safari: return "Safari"
        case .tropical: return "Tropical / Hawaïen"
        case .countryWestern: return "Country / Western"
        case .baroque: return "Baroque"
        case .minimalist: return "Minimalist"
        case .underground: return "Underground"
        case .hauteCouture: return "Haute Couture"
        }
    }
}