// Sources/SHIFT/EstablishmentType.swift
// E-ROK-Package
//
// Created by Fabien Koré on 13/07/2025.

import Foundation

public enum EstablishmentType: String, Codable, CaseIterable, Identifiable {
    case bar = "Bar"
    case nightClub = "Boîte de nuit"
    case receptionHall = "Salle de réception"
    case homeParty = "Home party"
    case restaurant = "Restaurant"
    case privateClub = "Club privé"
    case festival = "Festival"
    case barRestaurant = "Bar restaurant"
    case dancingBar = "Bar dansant"
    case multiRoomClub = "Club multi-salles"
    case lounge = "Lounge"
    case rooftop = "Rooftop"
    case beachClub = "Beach club"
    case karaokeBar = "Karaoke bar"
    case liveMusicVenue = "Salle de musique live"
    case concertHall = "Salle de concert"
    case sportsBar = "Sports bar"
    case wineBar = "Bar à vin"
    case brewery = "Brasserie"
    case eventVenue = "Lieu événementiel"
    case poolClub = "Pool Club"
    case speakeasy = "Speakeasy"
    case jazzClub = "Club de jazz"
    case comedyClub = "Club de comédie"
    case cigarLounge = "Salon à cigares"
    case hookahLounge = "Salon à chicha"
    case diveBar = "Bar populaire"
    case gastropub = "Gastropub"
    case cocktailBar = "Bar à cocktails"
    case tikiBar = "Bar tiki"
    case rooftopBar = "Bar sur le toit"
    case beachResort = "Resort de plage"
    case yachtClub = "Club nautique"
    case casino = "Casino"
    case danceStudio = "Studio de danse"
    case artGallery = "Galerie d'art"
    case popUpVenue = "Lieu pop-up"
    case rooftopLounge = "Lounge sur le toit"
    case terraceBar = "Bar en terrasse"
    case rooftopRestaurant = "Restaurant sur le toit"
    case outdoorVenue = "Lieu en plein air"
    case vineyard = "Vignoble"
    case distillery = "Distillerie"
    case taproom = "Taproom"
    case pianoBar = "Piano bar"
    case bluesClub = "Club de blues"
    case rockClub = "Club de rock"
    case hipHopClub = "Club hip-hop"
    case latinClub = "Club latino"
    case salsaClub = "Club de salsa"
    case reggaeClub = "Club reggae"
    case edmClub = "Club EDM"
    case technoClub = "Club techno"
    case houseClub = "Club house"
    case arcadeBar = "Bar d'arcade"
    case gameRoom = "Salle de jeux"
    case bowlingAlley = "Bowling"
    case poolHall = "Salle de billard"
    case cabaret = "Cabaret"
    case burlesqueVenue = "Lieu de burlesque"
    case supperClub = "Supper club"
    case rooftopPoolClub = "Club de piscine sur le toit"
    case beachBar = "Bar de plage"
    case tropicalBar = "Bar tropical"
    case rooftopNightClub = "Boîte de nuit sur le toit"
    case speakeasyLounge = "Lounge speakeasy"
    case culturalCenter = "Centre culturel"
    case rooftopEventSpace = "Espace événementiel sur le toit"
    case openAirClub = "Club en plein air"
    case rooftopTerrace = "Terrasse sur le toit"
    case boutiqueHotelBar = "Bar d'hôtel boutique"
    case microbrewery = "Microbrasserie"
    case themedBar = "Bar à thème"
    case speakeasyCocktailBar = "Bar à cocktails speakeasy"
    case urbanLounge = "Lounge urbain"
    case rooftopBrewery = "Brasserie sur le toit"
    case boatVenue = "Lieu sur bateau"

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .bar: return "Bar"
        case .nightClub: return "Boîte de nuit"
        case .receptionHall: return "Salle de réception"
        case .homeParty: return "Home party"
        case .restaurant: return "Restaurant"
        case .privateClub: return "Club privé"
        case .festival: return "Festival"
        case .barRestaurant: return "Bar restaurant"
        case .dancingBar: return "Bar dansant"
        case .multiRoomClub: return "Club multi-salles"
        case .lounge: return "Lounge"
        case .rooftop: return "Rooftop"
        case .beachClub: return "Beach club"
        case .karaokeBar: return "Karaoke bar"
        case .liveMusicVenue: return "Salle de musique live"
        case .concertHall: return "Salle de concert"
        case .sportsBar: return "Sports bar"
        case .wineBar: return "Bar à vin"
        case .brewery: return "Brasserie"
        case .eventVenue: return "Lieu événementiel"
        case .poolClub: return "Pool Club"
        case .speakeasy: return "Speakeasy"
        case .jazzClub: return "Club de jazz"
        case .comedyClub: return "Club de comédie"
        case .cigarLounge: return "Salon à cigares"
        case .hookahLounge: return "Salon à chicha"
        case .diveBar: return "Bar populaire"
        case .gastropub: return "Gastropub"
        case .cocktailBar: return "Bar à cocktails"
        case .tikiBar: return "Bar tiki"
        case .rooftopBar: return "Bar sur le toit"
        case .beachResort: return "Resort de plage"
        case .yachtClub: return "Club nautique"
        case .casino: return "Casino"
        case .danceStudio: return "Studio de danse"
        case .artGallery: return "Galerie d'art"
        case .popUpVenue: return "Lieu pop-up"
        case .rooftopLounge: return "Lounge sur le toit"
        case .terraceBar: return "Bar en terrasse"
        case .rooftopRestaurant: return "Restaurant sur le toit"
        case .outdoorVenue: return "Lieu en plein air"
        case .vineyard: return "Vignoble"
        case .distillery: return "Distillerie"
        case .taproom: return "Taproom"
        case .pianoBar: return "Piano bar"
        case .bluesClub: return "Club de blues"
        case .rockClub: return "Club de rock"
        case .hipHopClub: return "Club hip-hop"
        case .latinClub: return "Club latino"
        case .salsaClub: return "Club de salsa"
        case .reggaeClub: return "Club reggae"
        case .edmClub: return "Club EDM"
        case .technoClub: return "Club techno"
        case .houseClub: return "Club house"
        case .arcadeBar: return "Bar d'arcade"
        case .gameRoom: return "Salle de jeux"
        case .bowlingAlley: return "Bowling"
        case .poolHall: return "Salle de billard"
        case .cabaret: return "Cabaret"
        case .burlesqueVenue: return "Lieu de burlesque"
        case .supperClub: return "Supper club"
        case .rooftopPoolClub: return "Club de piscine sur le toit"
        case .beachBar: return "Bar de plage"
        case .tropicalBar: return "Bar tropical"
        case .rooftopNightClub: return "Boîte de nuit sur le toit"
        case .speakeasyLounge: return "Lounge speakeasy"
        case .culturalCenter: return "Centre culturel"
        case .rooftopEventSpace: return "Espace événementiel sur le toit"
        case .openAirClub: return "Club en plein air"
        case .rooftopTerrace: return "Terrasse sur le toit"
        case .boutiqueHotelBar: return "Bar d'hôtel boutique"
        case .microbrewery: return "Microbrasserie"
        case .themedBar: return "Bar à thème"
        case .speakeasyCocktailBar: return "Bar à cocktails speakeasy"
        case .urbanLounge: return "Lounge urbain"
        case .rooftopBrewery: return "Brasserie sur le toit"
        case .boatVenue: return "Lieu sur bateau"
        }

    public var isFeminine: Bool {
        switch self {
        case .nightClub, .receptionHall, .liveMusicVenue, .concertHall, .gameRoom, .poolHall, .rooftopTerrace, .artGallery, .rooftopNightClub:
            return true // Féminin : "une Boîte de nuit", "une Salle de réception", etc.
        default:
            return false // Masculin : "un Bar", "un Restaurant", etc.
        }
    }
}