//
//  EventType.swift
//  E-ROK-Package
//
//  Created by Fabien Koré on 27/09/2025.
//


// Sources/SHIFT/EventType.swift
// E-ROK-Package
//
// Created by Fabien Koré on 06/09/2025.

import Foundation

public enum EventType: String, Codable, CaseIterable, Identifiable {
    case soiree = "Soirée"
    case specialSoiree = "Soirée Spéciale"
    case showcase = "Showcase"
    case before = "Before"
    case after = "After"
    case openMic = "Open Mic"
    case themedNight = "Soirée à Thème"
    case liveConcert = "Concert Live"
    case djSet = "DJ Set"
    case launchParty = "Soirée de Lancement"
    case networking = "Networking"
    case privateEvent = "Événement Privé"
    case clubNight = "Soirée Club"
    case rooftopParty = "Rooftop Party"
    case beachParty = "Beach Party"
    case poolParty = "Pool Party"
    case karaokeNight = "Karaoke Night"
    case ladiesNight = "Ladies Night"
    case gentlemenNight = "Gentlemen Night"
    case prideNight = "Pride Night"
    case charityEvent = "Événement Caritatif"
    case festivalNight = "Soirée Festival"
    case popUpEvent = "Événement Pop-Up"
    case artExhibition = "Exposition Artistique"
    case sportsViewing = "Soirée Sportive"
    case comedyNight = "Soirée Comédie"
    case wineTasting = "Dégustation de Vin"
    case cocktailNight = "Soirée Cocktails"
    case costumeParty = "Soirée Costumée"
    case glowParty = "Glow Party"
    case neonNight = "Neon Night"
    case retroNight = "Retro Night"
    case eightiesNight = "Soirée Années 80"
    case ninetiesNight = "Soirée Années 90"
    case twoThousandsNight = "Soirée Années 2000"
    case hipHopNight = "Soirée Hip-Hop"
    case reggaeNight = "Soirée Reggae"
    case latinNight = "Soirée Latine"
    case jazzNight = "Soirée Jazz"
    case bluesNight = "Soirée Blues"
    case rockNight = "Soirée Rock"
    case popNight = "Soirée Pop"
    case edmNight = "Soirée EDM"
    case technoNight = "Soirée Techno"
    case houseNight = "Soirée House"
    case tranceNight = "Soirée Trance"
    case salsaNight = "Soirée Salsa"
    case bachataNight = "Soirée Bachata"
    case masqueradeBall = "Bal Masqué"
    case halloweenParty = "Soirée Halloween"
    case christmasParty = "Soirée de Noël"
    case newYearParty = "Soirée du Nouvel An"
    case valentinesNight = "Soirée Saint-Valentin"
    case stPatrickParty = "Soirée Saint-Patrick"
    case easterParty = "Soirée de Pâques"
    case summerKickoff = "Lancement de l'Été"
    case backToSchoolParty = "Soirée de Rentrée"
    case thanksgivingParty = "Soirée Thanksgiving"
    case blackFridayParty = "Soirée Black Friday"
    case winterWonderland = "Soirée Pays des Merveilles Hivernal"
    case casinoNight = "Soirée Casino"
    case greatGatsbyNight = "Soirée Gatsby le Magnifique"
    case hollywoodNight = "Soirée Hollywood"
    case tropicalNight = "Soirée Tropicale"
    case carnivalNight = "Soirée Carnaval"
    case pirateParty = "Soirée Pirates"
    case westernNight = "Soirée Western"
    case luauParty = "Soirée Hawaïenne"
    case superheroesNight = "Soirée Super-Héros"
    case fairyTaleNight = "Soirée Contes de Fées"
    case spaceNight = "Soirée Espace"
    case fashionShowNight = "Soirée Défilé de Mode"
    case burlesqueNight = "Soirée Burlesque"
    case silentDisco = "Silent Disco"
    case rooftopRave = "Rave sur le Toit"
    case boatParty = "Soirée en Bateau"
    case speakeasyNight = "Soirée Speakeasy"
    case acousticNight = "Soirée Acoustique"
    
    public var id: String { rawValue }
    
    public var displayName: String {
        switch self {
        case .soiree: return "Soirée"
        case .specialSoiree: return "Soirée Spéciale"
        case .showcase: return "Showcase"
        case .before: return "Before"
        case .after: return "After"
        case .openMic: return "Open Mic"
        case .themedNight: return "Soirée à Thème"
        case .liveConcert: return "Concert Live"
        case .djSet: return "DJ Set"
        case .launchParty: return "Soirée de Lancement"
        case .networking: return "Networking"
        case .privateEvent: return "Événement Privé"
        case .clubNight: return "Soirée Club"
        case .rooftopParty: return "Rooftop Party"
        case .beachParty: return "Beach Party"
        case .poolParty: return "Pool Party"
        case .karaokeNight: return "Karaoke Night"
        case .ladiesNight: return "Ladies Night"
        case .gentlemenNight: return "Gentlemen Night"
        case .prideNight: return "Pride Night"
        case .charityEvent: return "Événement Caritatif"
        case .festivalNight: return "Soirée Festival"
        case .popUpEvent: return "Événement Pop-Up"
        case .artExhibition: return "Exposition Artistique"
        case .sportsViewing: return "Soirée Sportive"
        case .comedyNight: return "Soirée Comédie"
        case .wineTasting: return "Dégustation de Vin"
        case .cocktailNight: return "Soirée Cocktails"
        case .costumeParty: return "Soirée Costumée"
        case .glowParty: return "Glow Party"
        case .neonNight: return "Neon Night"
        case .retroNight: return "Retro Night"
        case .eightiesNight: return "Soirée Années 80"
        case .ninetiesNight: return "Soirée Années 90"
        case .twoThousandsNight: return "Soirée Années 2000"
        case .hipHopNight: return "Soirée Hip-Hop"
        case .reggaeNight: return "Soirée Reggae"
        case .latinNight: return "Soirée Latine"
        case .jazzNight: return "Soirée Jazz"
        case .bluesNight: return "Soirée Blues"
        case .rockNight: return "Soirée Rock"
        case .popNight: return "Soirée Pop"
        case .edmNight: return "Soirée EDM"
        case .technoNight: return "Soirée Techno"
        case .houseNight: return "Soirée House"
        case .tranceNight: return "Soirée Trance"
        case .salsaNight: return "Soirée Salsa"
        case .bachataNight: return "Soirée Bachata"
        case .masqueradeBall: return "Bal Masqué"
        case .halloweenParty: return "Soirée Halloween"
        case .christmasParty: return "Soirée de Noël"
        case .newYearParty: return "Soirée du Nouvel An"
        case .valentinesNight: return "Soirée Saint-Valentin"
        case .stPatrickParty: return "Soirée Saint-Patrick"
        case .easterParty: return "Soirée de Pâques"
        case .summerKickoff: return "Lancement de l'Été"
        case .backToSchoolParty: return "Soirée de Rentrée"
        case .thanksgivingParty: return "Soirée Thanksgiving"
        case .blackFridayParty: return "Soirée Black Friday"
        case .winterWonderland: return "Soirée Pays des Merveilles Hivernal"
        case .casinoNight: return "Soirée Casino"
        case .greatGatsbyNight: return "Soirée Gatsby le Magnifique"
        case .hollywoodNight: return "Soirée Hollywood"
        case .tropicalNight: return "Soirée Tropicale"
        case .carnivalNight: return "Soirée Carnaval"
        case .pirateParty: return "Soirée Pirates"
        case .westernNight: return "Soirée Western"
        case .luauParty: return "Soirée Hawaïenne"
        case .superheroesNight: return "Soirée Super-Héros"
        case .fairyTaleNight: return "Soirée Contes de Fées"
        case .spaceNight: return "Soirée Espace"
        case .fashionShowNight: return "Soirée Défilé de Mode"
        case .burlesqueNight: return "Soirée Burlesque"
        case .silentDisco: return "Silent Disco"
        case .rooftopRave: return "Rave sur le Toit"
        case .boatParty: return "Soirée en Bateau"
        case .speakeasyNight: return "Soirée Speakeasy"
        case .acousticNight: return "Soirée Acoustique"
        }
        
         
    }
    public var isFeminine: Bool {
       switch self {
       case .soiree, .specialSoiree, .themedNight, .clubNight, .rooftopParty, .beachParty, .poolParty, .karaokeNight, .ladiesNight, .gentlemenNight, .prideNight, .festivalNight, .comedyNight, .cocktailNight, .costumeParty, .glowParty, .neonNight, .retroNight, .eightiesNight, .ninetiesNight, .twoThousandsNight, .hipHopNight, .reggaeNight, .latinNight, .jazzNight, .bluesNight, .rockNight, .popNight, .edmNight, .technoNight, .houseNight, .tranceNight, .salsaNight, .bachataNight, .halloweenParty, .christmasParty, .newYearParty, .valentinesNight, .stPatrickParty, .easterParty, .backToSchoolParty, .thanksgivingParty, .blackFridayParty, .winterWonderland, .greatGatsbyNight, .hollywoodNight, .tropicalNight, .carnivalNight, .pirateParty, .westernNight, .luauParty, .superheroesNight, .fairyTaleNight, .spaceNight, .fashionShowNight, .burlesqueNight:
           return true // Féminin : "une Soirée", "une Soirée Club", etc.
       default:
           return false // Masculin : "un Concert Live", "un Showcase", etc.
       }
   }
}
