// Sources/SHIFT/ServiceType.swift
// E-ROK-Package
//
// Created by Fabien Koré on 07/09/2025.

import Foundation

public enum ServiceType: String, Codable, CaseIterable, Identifiable {
    case bottles = "Bouteille"
    case bottlePack = "Pack de bouteilles"
    case allInclusive = "All inclusives"
    case privateDance = "Danses privées"
    case vipSpaces = "Espaces VIP"
    case fastPass = "Entrée prioritaire"
    case standardTable = "Table standard"
    case vipTable = "Table VIP"
    case customCocktails = "Cocktails sur mesure"
    case champagneService = "Service de champagne"
    case shotsService = "Service de shots"
    case foodService = "Service de restauration"
    case hookahService = "Service de narguilé"
    case privateRoomRental = "Location de salle privée"
    case backstageAccess = "Accès backstage"
    case unlimitedDrinks = "Boissons illimitées"
    case cocktailPackage = "Forfait cocktails"
    case verre = "Verre"
    case consommation = "Consommation"
    case pourboire = "Pourboire"
    case entrée = "Entrée"
    case freePass = "Pass gratuit"
    case bottleUp = "Pack Bottle Up"
    case allIn = "Pack All In"
    case vipExperience = "Expérience VIP"
    case partyPack = "Pack Party"
    case groupPack = "Pack Groupe"
    case luxuryPack = "Pack Luxe"
    case chillPack = "Pack Chill"
    case softDrink = "Boisson non alcoolisée"
    case premiumCocktail = "Cocktail premium"
    case snack = "Snack"
    case premiumBottle = "Bouteille premium"
    case shotTray = "Plateau de shots"
    case mocktail = "Mocktail"
    case energyDrink = "Boisson énergétique"
    case happyHourPack = "Pack Happy Hour"
    case danceFloorPack = "Pack Piste de danse"
    case premiumVipPack = "Pack VIP Premium"
    case nightOwlPack = "Pack Night Owl"
    case celebrationPack = "Pack Célébration"
    case groupVipPack = "Pack Groupe VIP"
    case chillVipPack = "Pack Chill VIP"
    case barHopperPack = "Pack Bar Hopper"

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .bottles: return "Bouteille (vodka, whisky, etc.)"
        case .bottlePack: return "Pack de bouteilles (plusieurs bouteilles)"
        case .allInclusive: return "All inclusives (entrée + bouteilles + services + fast pass)"
        case .privateDance: return "Danses privées avec performeur"
        case .vipSpaces: return "Accès aux espaces VIP"
        case .fastPass: return "Entrée prioritaire (sans file d’attente)"
        case .standardTable: return "Table standard (4-6 personnes)"
        case .vipTable: return "Table VIP (6-8 personnes, emplacement privilégié)"
        case .customCocktails: return "Cocktails sur mesure"
        case .champagneService: return "Service de champagne (bouteille + service)"
        case .shotsService: return "Service de shots (par shot)"
        case .foodService: return "Service de restauration (repas complet)"
        case .hookahService: return "Service de narguilé"
        case .privateRoomRental: return "Location de salle privée"
        case .backstageAccess: return "Accès backstage (rencontre artistes)"
        case .unlimitedDrinks: return "Boissons illimitées (pendant un créneau)"
        case .cocktailPackage: return "Forfait cocktails (plusieurs cocktails)"
        case .verre: return "Verre (boisson individuelle)"
        case .consommation: return "Consommation (boisson ou aliment)"
        case .pourboire: return "Pourboire (pour le personnel)"
        case .entrée: return "Entrée standard"
        case .freePass: return "Pass gratuit (entrée gratuite)"
        case .bottleUp: return "Pack Bottle Up (entrée + 1 bouteille)"
        case .allIn: return "Pack All In (entrée + bouteille + vestiaire)"
        case .vipExperience: return "Expérience VIP (entrée VIP + table VIP + bouteille)"
        case .partyPack: return "Pack Party (entrée + consommation + fast pass)"
        case .groupPack: return "Pack Groupe (entrée pour 4 personnes + bouteille)"
        case .luxuryPack: return "Pack Luxe (entrée VIP + table VIP + bouteille premium + fast pass)"
        case .chillPack: return "Pack Chill (entrée + consommation + accès zone chill)"
        case .softDrink: return "Boisson non alcoolisée (soda, jus)"
        case .premiumCocktail: return "Cocktail premium (signature du bar)"
        case .snack: return "Snack (tapas, nachos, etc.)"
        case .premiumBottle: return "Bouteille premium (champagne haut de gamme)"
        case .shotTray: return "Plateau de shots (pour groupe)"
        case .mocktail: return "Mocktail (cocktail sans alcool)"
        case .energyDrink: return "Boisson énergétique (Red Bull, etc.)"
        case .happyHourPack: return "Pack Happy Hour (entrée + 2 consommations à prix réduit)"
        case .danceFloorPack: return "Pack Piste de danse (entrée + accès prioritaire piste + consommation)"
        case .premiumVipPack: return "Pack VIP Premium (entrée VIP + table VIP + bouteille premium + service dédié)"
        case .nightOwlPack: return "Pack Night Owl (entrée tardive après minuit + 1 consommation)"
        case .celebrationPack: return "Pack Célébration (entrée + bouteille + dessert)"
        case .groupVipPack: return "Pack Groupe VIP (entrée VIP pour 6 personnes + table VIP + 2 bouteilles)"
        case .chillVipPack: return "Pack Chill VIP (entrée + accès zone chill + cocktail premium)"
        case .barHopperPack: return "Pack Bar Hopper (entrée multi-établissements + 1 consommation par lieu)"
        }
    }
}