//
//  ServiceType.swift
//  E-ROK-Package
//
//  Created by Fabien Koré on 27/09/2025.
//


// Sources/SHIFT/ServiceType.swift
// E-ROK-Package
//
// Created by Fabien Koré on 07/09/2025.

import Foundation

public enum ServiceType: String, Codable, CaseIterable, Identifiable {
    case bottles = "Bouteille"
    case bottlePack = "Pack de bouteilles"
    case allInclusive = "All inclusives"
    case privateDance = "Danses privées"
    case vipSpaces = "Espaces VIP"
    case fastPass = "Entrée prioritaire"
    case standardTable = "Table standard"
    case vipTable = "Table VIP"
    case customCocktails = "Cocktails sur mesure"
    case champagneService = "Service de champagne"
    case shotsService = "Service de shots"
    case foodService = "Service de restauration"
    case hookahService = "Service de narguilé"
    case privateRoomRental = "Location de salle privée"
    case backstageAccess = "Accès backstage"
    case unlimitedDrinks = "Boissons illimitées"
    case cocktailPackage = "Forfait cocktails"
    case verre = "Verre"
    case consommation = "Consommation"
    case pourboire = "Pourboire"
    case entrée = "Entrée"
    case freePass = "Pass gratuit"
    case bottleUp = "Pack Bottle Up"
    case allIn = "Pack All In"
    case vipExperience = "Expérience VIP"
    case partyPack = "Pack Party"
    case groupPack = "Pack Groupe"
    case luxuryPack = "Pack Luxe"
    case chillPack = "Pack Chill"
    case softDrink = "Boisson non alcoolisée"
    case premiumCocktail = "Cocktail premium"
    case snack = "Snack"
    case premiumBottle = "Bouteille premium"
    case shotTray = "Plateau de shots"
    case mocktail = "Mocktail"
    case energyDrink = "Boisson énergétique"
    case happyHourPack = "Pack Happy Hour"
    case danceFloorPack = "Pack Piste de danse"
    case premiumVipPack = "Pack VIP Premium"
    case nightOwlPack = "Pack Night Owl"
    case celebrationPack = "Pack Célébration"
    case groupVipPack = "Pack Groupe VIP"
    case chillVipPack = "Pack Chill VIP"
    case barHopperPack = "Pack Bar Hopper"
    case birthdayPackage = "Pack Anniversaire"
    case bachelorPartyPack = "Pack EVG / EVJF"
    case vipBalconyRental = "Location de balcon VIP"
    case djBoothVipTable = "Table VIP Cabine DJ"
    case vipHostess = "Hôtesse d'accueil dédiée"
    case dedicatedWaiter = "Serveur dédié"
    case bodyguardPrivate = "Garde du corps privé"
    case limoTransfer = "Transfert en limousine"
    case valetParkingService = "Service de voiturier"
    case shishaPremium = "Chicha premium"
    case cigarService = "Service de cigares"
    case professionalPhotoSession = "Shooting photo pro"
    case customLedMessage = "Message LED personnalisé"
    case champagneShowers = "Show Champagne / Show Bouteille"
    case afterPartyAccess = "Accès After-Party"
    case vipCloakroom = "Vestiaire VIP"
    case privateDj = "DJ privé"
    case bartenderPrivate = "Barman privé"
    case tastingFlight = "Dégustation thématique"
    case sushiPlatter = "Plateau de sushis"
    case caviarService = "Service de caviar"
    case mixologyWorkshop = "Atelier mixologie"
    case earlyEntry = "Entrée anticipée"

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .bottles: return "Bouteille (vodka, whisky, etc.)"
        case .bottlePack: return "Pack de bouteilles (plusieurs bouteilles)"
        case .allInclusive: return "All inclusives (entrée + bouteilles + services + fast pass)"
        case .privateDance: return "Danses privées avec performeur"
        case .vipSpaces: return "Accès aux espaces VIP"
        case .fastPass: return "Entrée prioritaire (sans file d’attente)"
        case .standardTable: return "Table standard (4-6 personnes)"
        case .vipTable: return "Table VIP (6-8 personnes, emplacement privilégié)"
        case .customCocktails: return "Cocktails sur mesure"
        case .champagneService: return "Service de champagne (bouteille + service)"
        case .shotsService: return "Service de shots (par shot)"
        case .foodService: return "Service de restauration (repas complet)"
        case .hookahService: return "Service de narguilé"
        case .privateRoomRental: return "Location de salle privée"
        case .backstageAccess: return "Accès backstage (rencontre artistes)"
        case .unlimitedDrinks: return "Boissons illimitées (pendant un créneau)"
        case .cocktailPackage: return "Forfait cocktails (plusieurs cocktails)"
        case .verre: return "Verre (boisson individuelle)"
        case .consommation: return "Consommation (boisson ou aliment)"
        case .pourboire: return "Pourboire (pour le personnel)"
        case .entrée: return "Entrée standard"
        case .freePass: return "Pass gratuit (entrée gratuite)"
        case .bottleUp: return "Pack Bottle Up (entrée + 1 bouteille)"
        case .allIn: return "Pack All In (entrée + bouteille + vestiaire)"
        case .vipExperience: return "Expérience VIP (entrée VIP + table VIP + bouteille)"
        case .partyPack: return "Pack Party (entrée + consommation + fast pass)"
        case .groupPack: return "Pack Groupe (entrée pour 4 personnes + bouteille)"
        case .luxuryPack: return "Pack Luxe (entrée VIP + table VIP + bouteille premium + fast pass)"
        case .chillPack: return "Pack Chill (entrée + consommation + accès zone chill)"
        case .softDrink: return "Boisson non alcoolisée (soda, jus)"
        case .premiumCocktail: return "Cocktail premium (signature du bar)"
        case .snack: return "Snack (tapas, nachos, etc.)"
        case .premiumBottle: return "Bouteille premium (champagne haut de gamme)"
        case .shotTray: return "Plateau de shots (pour groupe)"
        case .mocktail: return "Mocktail (cocktail sans alcool)"
        case .energyDrink: return "Boisson énergétique (Red Bull, etc.)"
        case .happyHourPack: return "Pack Happy Hour (entrée + 2 consommations à prix réduit)"
        case .danceFloorPack: return "Pack Piste de danse (entrée + accès prioritaire piste + consommation)"
        case .premiumVipPack: return "Pack VIP Premium (entrée VIP + table VIP + bouteille premium + service dédié)"
        case .nightOwlPack: return "Pack Night Owl (entrée tardive après minuit + 1 consommation)"
        case .celebrationPack: return "Pack Célébration (entrée + bouteille + dessert)"
        case .groupVipPack: return "Pack Groupe VIP (entrée VIP pour 6 personnes + table VIP + 2 bouteilles)"
        case .chillVipPack: return "Pack Chill VIP (entrée + accès zone chill + cocktail premium)"
        case .barHopperPack: return "Pack Bar Hopper (entrée multi-établissements + 1 consommation par lieu)"
        case .birthdayPackage: return "Pack Anniversaire (bouteille offerte + gâteau + bougies)"
        case .bachelorPartyPack: return "Pack Enterrement de vie de garçon/jeune fille (services dédiés, surprises)"
        case .vipBalconyRental: return "Location privative de balcon VIP"
        case .djBoothVipTable: return "Table VIP Cabine DJ (emplacement ultra-exclusif)"
        case .vipHostess: return "Service d'accueil et d'accompagnement VIP dédié"
        case .dedicatedWaiter: return "Serveur exclusif pour votre table"
        case .bodyguardPrivate: return "Sécurité rapprochée privée"
        case .limoTransfer: return "Transfert en limousine ou véhicule de luxe"
        case .valetParkingService: return "Service de voiturier"
        case .shishaPremium: return "Chicha premium (parfums exclusifs)"
        case .cigarService: return "Service de cigares d'exception"
        case .professionalPhotoSession: return "Shooting photo privé par le photographe du lieu"
        case .customLedMessage: return "Message LED personnalisé sur les écrans géants"
        case .champagneShowers: return "Show Champagne / Show Bouteille (feux de Bengale et performeurs)"
        case .afterPartyAccess: return "Accès After-Party officiel"
        case .vipCloakroom: return "Vestiaire VIP prioritaire gratuit"
        case .privateDj: return "DJ privé dédié"
        case .bartenderPrivate: return "Barman privé dédié"
        case .tastingFlight: return "Plateau de dégustation commentée de spiritueux"
        case .sushiPlatter: return "Plateau de sushis et sashimis frais"
        case .caviarService: return "Service de caviar d'exception"
        case .mixologyWorkshop: return "Atelier mixologie d'initiation aux cocktails"
        case .earlyEntry: return "Entrée anticipée avant l'ouverture officielle"
        }
    }
}