//
//  VenueFeature.swift
//  E-ROK-Package
//
//  Created by Fabien Koré on 27/09/2025.
//


// Sources/SHIFT/VenueFeature.swift
// E-ROK-Package
//
// Created by Fabien Koré on 06/09/2025.

import Foundation

public enum VenueFeature: String, Codable, CaseIterable, Identifiable {
    case danceFloor = "Piste de danse"
    case vipArea = "Carré VIP"
    case barCounter = "Comptoir de bar"
    case loungeArea = "Espace lounge"
    case terrace = "Terrasse"
    case rooftop = "Rooftop"
    case stage = "Scène"
    case privateRoom = "Salle privée"
    case smokingArea = "Espace fumeur"
    case cloakroom = "Vestiaire"
    case outdoorArea = "Espace extérieur"
    case pool = "Piscine"
    case restaurantArea = "Espace restaurant"
    case karaokeRoom = "Salle de karaoké"
    case gamingArea = "Espace de jeux"
    case hookahLounge = "Salon à chicha"
    case liveMusicStage = "Scène pour musique live"
    case djBooth = "Cabine DJ"
    case cocktailBar = "Bar à cocktails"
    case wineCellar = "Cave à vin"
    case arcadeRoom = "Salle d'arcade"
    case photoBooth = "Photobooth"
    case chillZone = "Zone chill"
    case vipLounge = "Lounge VIP"
    case speakeasy = "Speakeasy (Bar caché)"
    case secretEntrance = "Entrée secrète"
    case garden = "Jardin"
    case patio = "Patio"
    case beachAccess = "Accès plage"
    case beachCabana = "Cabane de plage"
    case vipBalcony = "Balcon VIP"
    case mezzanine = "Mezzanine"
    case cigarLounge = "Salon à cigares"
    case beerGarden = "Beer Garden"
    case shotBar = "Bar à shots"
    case champagneBar = "Bar à champagne"
    case whiskeyBar = "Bar à whisky"
    case rooftopPool = "Piscine sur le toit"
    case jacuzzi = "Jacuzzi"
    case backstage = "Coulisses / Backstage"
    case valetParking = "Service voiturier"
    case privateParking = "Parking privé"
    case ledCeiling = "Plafond LED interactif"
    case giantScreen = "Écran géant / Vidéo-projection"
    case highEndSoundSystem = "Système son haut de gamme"
    case laserShow = "Show laser"
    case co2Cannons = "Canons à CO2"
    case foamMachine = "Machine à mousse"
    case firePits = "Braseros / Cheminée extérieure"
    case panoramicView = "Vue panoramique"
    case billiardTables = "Tables de billard"
    case dartsSpace = "Espace fléchettes"
    case bowlingAlleys = "Pistes de bowling"
    case artGallery = "Galerie d'art"
    case privateKaraokeBox = "Box karaoké privé"
    case vipTables = "Tables VIP réservées"
    case outdoorBar = "Bar extérieur"
    case podium = "Podiums de danse"
    case waterfront = "Front de mer / Bord de l'eau"
    case secureEntrance = "Entrée hautement sécurisée"
    case infinityPool = "Piscine à débordement"
    case vipEntrance = "Entrée VIP dédiée"
    case privateBeach = "Plage privée"
    case champagneRoom = "Salon Champagne"
    case cigarRoom = "Cigar Room (Fumoir)"
    case showCooking = "Station Live Cooking"
    case elevatedDjBooth = "Cabine DJ suspendue"
    case vipRestrooms = "Toilettes VIP privées"
    case helipad = "Héliport"
    case boatDock = "Ponton d'amarrage"
    case giantAquarium = "Mur aquarium géant"
    case waterfall = "Cascade / Mur d'eau"
    case outdoorDanceFloor = "Piste de danse extérieure"
    case hiddenRoom = "Salle secrète"
    case glassFloor = "Sol en verre"
    case retractableRoof = "Toit rétractable"

    public var id: String { rawValue }

    public var displayName: String {
        switch self {
        case .danceFloor: return "Piste de danse"
        case .vipArea: return "Carré VIP"
        case .barCounter: return "Comptoir de bar"
        case .loungeArea: return "Espace lounge"
        case .terrace: return "Terrasse"
        case .rooftop: return "Rooftop"
        case .stage: return "Scène"
        case .privateRoom: return "Salle privée"
        case .smokingArea: return "Espace fumeur"
        case .cloakroom: return "Vestiaire"
        case .outdoorArea: return "Espace extérieur"
        case .pool: return "Piscine"
        case .restaurantArea: return "Espace restaurant"
        case .karaokeRoom: return "Salle de karaoké"
        case .gamingArea: return "Espace de jeux"
        case .hookahLounge: return "Salon à chicha"
        case .liveMusicStage: return "Scène pour musique live"
        case .djBooth: return "Cabine DJ"
        case .cocktailBar: return "Bar à cocktails"
        case .wineCellar: return "Cave à vin"
        case .arcadeRoom: return "Salle d'arcade"
        case .photoBooth: return "Photobooth"
        case .chillZone: return "Zone chill"
        case .vipLounge: return "Lounge VIP"
        case .speakeasy: return "Speakeasy (Bar caché)"
        case .secretEntrance: return "Entrée secrète"
        case .garden: return "Jardin"
        case .patio: return "Patio"
        case .beachAccess: return "Accès plage"
        case .beachCabana: return "Cabane de plage"
        case .vipBalcony: return "Balcon VIP"
        case .mezzanine: return "Mezzanine"
        case .cigarLounge: return "Salon à cigares"
        case .beerGarden: return "Beer Garden"
        case .shotBar: return "Bar à shots"
        case .champagneBar: return "Bar à champagne"
        case .whiskeyBar: return "Bar à whisky"
        case .rooftopPool: return "Piscine sur le toit"
        case .jacuzzi: return "Jacuzzi"
        case .backstage: return "Coulisses / Backstage"
        case .valetParking: return "Service voiturier"
        case .privateParking: return "Parking privé"
        case .ledCeiling: return "Plafond LED interactif"
        case .giantScreen: return "Écran géant / Vidéo-projection"
        case .highEndSoundSystem: return "Système son haut de gamme"
        case .laserShow: return "Show laser"
        case .co2Cannons: return "Canons à CO2"
        case .foamMachine: return "Machine à mousse"
        case .firePits: return "Braseros / Cheminée extérieure"
        case .panoramicView: return "Vue panoramique"
        case .billiardTables: return "Tables de billard"
        case .dartsSpace: return "Espace fléchettes"
        case .bowlingAlleys: return "Pistes de bowling"
        case .artGallery: return "Galerie d'art"
        case .privateKaraokeBox: return "Box karaoké privé"
        case .vipTables: return "Tables VIP réservées"
        case .outdoorBar: return "Bar extérieur"
        case .podium: return "Podiums de danse"
        case .waterfront: return "Front de mer / Bord de l'eau"
        case .secureEntrance: return "Entrée hautement sécurisée"
        case .infinityPool: return "Piscine à débordement"
        case .vipEntrance: return "Entrée VIP dédiée"
        case .privateBeach: return "Plage privée"
        case .champagneRoom: return "Salon Champagne"
        case .cigarRoom: return "Cigar Room (Fumoir)"
        case .showCooking: return "Station Live Cooking / Show culinaire"
        case .elevatedDjBooth: return "Cabine DJ suspendue / surélevée"
        case .vipRestrooms: return "Toilettes VIP privées"
        case .helipad: return "Héliport"
        case .boatDock: return "Ponton d'amarrage (Bateau)"
        case .giantAquarium: return "Mur aquarium géant"
        case .waterfall: return "Cascade / Mur d'eau décoratif"
        case .outdoorDanceFloor: return "Piste de danse extérieure"
        case .hiddenRoom: return "Salle secrète"
        case .glassFloor: return "Sol en verre"
        case .retractableRoof: return "Toit rétractable"
        }
    }
}