// Sources/MYMECA/SpecialiteGarage.swift
// E-ROK-Package
//
// Created by Fabien Koré on 26/03/2025.

import Foundation

public enum SpecialiteGarage: String, Codable, CaseIterable, Identifiable {
    // Spécialités existantes
    case mecaniqueGenerale = "Mécanique générale"
    case carrosserie = "Carrosserie"
    case peinture = "Peinture"
    case electriciteAuto = "Électricité auto"
    case climatisation = "Climatisation"
    case pneus = "Pneus"
    case freins = "Freins"
    case diagnostic = "Diagnostic électronique"
    case moteur = "Réparation moteur"
    case transmission = "Transmission"
    case suspension = "Suspension"
    case echappement = "Échappement"
    case vitrage = "Vitrage"
    case tuning = "Tuning"
    case vehiculesElectriques = "Véhicules électriques"
    case controleTechnique = "Préparation contrôle technique"

    // Nouvelles spécialités (50 ajoutées)
    case reprogrammationECU = "Reprogrammation ECU"
    case alignementRoues = "Alignement des roues"
    case equilibragePneus = "Équilibrage des pneus"
    case reparationTurbo = "Réparation turbo"
    case remplacementEmbrayage = "Remplacement embrayage"
    case jointCulasse = "Remplacement joint de culasse"
    case reparationBoiteVitesse = "Réparation boîte de vitesse"
    case reparationBoiteAuto = "Réparation boîte automatique"
    case remplacementCardan = "Remplacement cardan"
    case reparationPompeEau = "Réparation pompe à eau"
    case remplacementRadiateur = "Remplacement radiateur"
    case nettoyageInjecteurs = "Nettoyage injecteurs"
    case reparationAlternateur = "Réparation alternateur"
    case remplacementDemarreur = "Remplacement démarreur"
    case reparationSystemeABS = "Réparation système ABS"
    case remplacementBougies = "Remplacement bougies"
    case remplacementFiltreAir = "Remplacement filtre à air"
    case remplacementFiltreCarburant = "Remplacement filtre à carburant"
    case reparationPompeCarburant = "Réparation pompe à carburant"
    case remplacementCourroieAlternateur = "Remplacement courroie d’alternateur"
    case reparationDirectionAssistee = "Réparation direction assistée"
    case remplacementAmortisseurs = "Remplacement amortisseurs"
    case reparationSystemeEchappement = "Réparation système d’échappement"
    case remplacementCatalyseur = "Remplacement catalyseur"
    case reparationVitreElectrique = "Réparation vitre électrique"
    case remplacementSerrurePorte = "Remplacement serrure de porte"
    case reparationRetroviseur = "Réparation rétroviseur"
    case rechargeClimatisation = "Recharge climatisation"
    case reparationCapteurParking = "Réparation capteur de parking"
    case remplacementCapteurOxigene = "Remplacement capteur d’oxygène"
    case reparationSystemeStartStop = "Réparation système start-stop"
    case reparationAntivolElectronique = "Réparation antivol électronique"
    case remplacementCapteurPluie = "Remplacement capteur de pluie"
    case reparationFeuxArriere = "Réparation feux arrière"
    case remplacementCapteurABS = "Remplacement capteur ABS"
    case reparationVerrouillageCentral = "Réparation verrouillage centralisé"
    case reparationFuiteDirection = "Réparation fuite direction assistée"
    case reparationRadiateurChauffage = "Réparation radiateur de chauffage"
    case remplacementCapteurAirbag = "Remplacement capteur d’airbag"
    case diagnosticBatterieHybride = "Diagnostic batterie hybride"
    case remplacementBatterieHybride = "Remplacement batterie hybride"
    case diagnosticOBD = "Diagnostic OBD"
    case restaurationVehiculeAncien = "Restauration véhicule ancien"
    case personnalisationEsthetique = "Personnalisation esthétique"
    case installationSystemeAudio = "Installation système audio"
    case traitementAntirouille = "Traitement antirouille"
    case remplacementPareChocs = "Remplacement pare-chocs"
    case reparationSystemeInjection = "Réparation système d’injection"
    case remplacementPompeHuile = "Remplacement pompe à huile"
    case reparationSuspensionPneumatique = "Réparation suspension pneumatique"
    case installationKitPerformance = "Installation kit performance"

    public var id: String { rawValue }
}
