//
//  VehicleBrand.swift
//  E-ROK-Package
//
//  Created by Fabien Koré on 27/09/2025.
//


// Sources/MYMECA/VehicleBrand.swift
// E-ROK-Package
//
// Created by Fabien Koré on 26/03/2025.

import Foundation

public enum VehicleBrand: String, Codable, CaseIterable, Identifiable {
    case acura = "Acura"
    case alfaRomeo = "Alfa Romeo"
    case alpine = "Alpine"
    case apollo = "Apollo"
    case ariel = "Ariel"
    case astonMartin = "Aston Martin"
    case audi = "Audi"
    case aurus = "Aurus"
    case bentley = "Bentley"
    case bmw = "BMW"
    case bollinger = "Bollinger"
    case borgward = "Borgward"
    case brilliance = "Brilliance"
    case bristol = "Bristol"
    case bugatti = "Bugatti"
    case buick = "Buick"
    case byd = "BYD"
    case cadillac = "Cadillac"
    case caterham = "Caterham"
    case chery = "Chery"
    case chevrolet = "Chevrolet"
    case chrysler = "Chrysler"
    case citroen = "Citroën"
    case cupra = "Cupra"
    case dacia = "Dacia"
    case daewoo = "Daewoo"
    case daihatsu = "Daihatsu"
    case dodge = "Dodge"
    case dongfeng = "Dongfeng"
    case ds = "DS"
    case eagle = "Eagle"
    case faradayFuture = "Faraday Future"
    case ferrari = "Ferrari"
    case fiat = "Fiat"
    case fisker = "Fisker"
    case ford = "Ford"
    case genesis = "Genesis"
    case geely = "Geely"
    case gmc = "GMC"
    case greatWall = "Great Wall"
    case haval = "Haval"
    case honda = "Honda"
    case hummer = "Hummer"
    case hyundai = "Hyundai"
    case infiniti = "Infiniti"
    case isuzu = "Isuzu"
    case jac = "JAC"
    case jaguar = "Jaguar"
    case jeep = "Jeep"
    case kia = "Kia"
    case koenigsegg = "Koenigsegg"
    case ktm = "KTM"
    case lada = "Lada"
    case lamborghini = "Lamborghini"
    case lancia = "Lancia"
    case landRover = "Land Rover"
    case lexus = "Lexus"
    case lincoln = "Lincoln"
    case lotus = "Lotus"
    case lucid = "Lucid"
    case lynkCo = "Lynk & Co"
    case mahindra = "Mahindra"
    case maserati = "Maserati"
    case maybach = "Maybach"
    case mazda = "Mazda"
    case mclaren = "McLaren"
    case mercedesBenz = "Mercedes-Benz"
    case mg = "MG"
    case mini = "Mini"
    case mitsubishi = "Mitsubishi"
    case morgan = "Morgan"
    case nio = "NIO"
    case nissan = "Nissan"
    case noble = "Noble"
    case oldsmobile = "Oldsmobile"
    case opel = "Opel"
    case pagani = "Pagani"
    case panoz = "Panoz"
    case peugeot = "Peugeot"
    case plymouth = "Plymouth"
    case polestar = "Polestar"
    case pontiac = "Pontiac"
    case porsche = "Porsche"
    case proton = "Proton"
    case ram = "RAM"
    case renault = "Renault"
    case rivian = "Rivian"
    case rollsRoyce = "Rolls-Royce"
    case saab = "Saab"
    case saleen = "Saleen"
    case saturn = "Saturn"
    case scion = "Scion"
    case seat = "SEAT"
    case shelby = "Shelby"
    case skoda = "Škoda"
    case smart = "Smart"
    case spykercars = "Spyker Cars"
    case ssangyong = "SsangYong"
    case subaru = "Subaru"
    case suzuki = "Suzuki"
    case tata = "Tata"
    case tesla = "Tesla"
    case toyota = "Toyota"
    case triumph = "Triumph"
    case tvr = "TVR"
    case vauxhall = "Vauxhall"
    case vinfast = "VinFast"
    case volkswagen = "Volkswagen"
    case volvo = "Volvo"
    case wiesmann = "Wiesmann"
    case workhorse = "Workhorse"
    case xpeng = "XPeng"
    case yamaha = "Yamaha"
    case zagato = "Zagato"
    case zotye = "Zotye"

    public var id: String { rawValue }
}